//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reco3Xml2Db.UI.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportXml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportXml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reco3Xml2Db.UI.Module.Properties.ImportXml", typeof(ImportXml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFilesCheckbox {
            get {
                return ResourceManager.GetString("AllFilesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process all files in the chosen directory with the same settings.
        /// </summary>
        public static string AllFilesToolTip {
            get {
                return ResourceManager.GetString("AllFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component exists. If you continue, an update will take place.
        /// </summary>
        public static string ComponentExistsInfo {
            get {
                return ResourceManager.GetString("ComponentExistsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Type: .
        /// </summary>
        public static string ComponentType {
            get {
                return ResourceManager.GetString("ComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename: .
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string OpenFileDialogButton {
            get {
                return ResourceManager.GetString("OpenFileDialogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string OpenPathDialogButton {
            get {
                return ResourceManager.GetString("OpenPathDialogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: .
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD Source: .
        /// </summary>
        public static string PDSource {
            get {
                return ResourceManager.GetString("PDSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD Status: .
        /// </summary>
        public static string PDStatus {
            get {
                return ResourceManager.GetString("PDStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace existing.
        /// </summary>
        public static string ReplaceCheckbox {
            get {
                return ResourceManager.GetString("ReplaceCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PD number exists in the database. The component will be added with reference to the source component.
        /// </summary>
        public static string SourceComponentExistsInfo {
            get {
                return ResourceManager.GetString("SourceComponentExistsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PD number already exists in the database. If this checkbox is checked, an Update will take place by replacing existing data for the existing component, as opposed to just adding this file, which is not present in the database, and referring to the existing component&apos;s PD Number.
        /// </summary>
        public static string UpdateExistingToolTip {
            get {
                return ResourceManager.GetString("UpdateExistingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to open a file dialog to browse for the Xml file(s).
        /// </summary>
        public static string XmlFileDialogButtonToolTip {
            get {
                return ResourceManager.GetString("XmlFileDialogButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to select file path to the Xml file(s).
        /// </summary>
        public static string XmlFilePathButtonToolTip {
            get {
                return ResourceManager.GetString("XmlFilePathButtonToolTip", resourceCulture);
            }
        }
    }
}
